CREATE TABLE "kira"."upload_cfg_msg" (
  "table_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "data_source_type" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_server_ip" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_username" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_password" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_local_name" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_remote_name" varchar(255) COLLATE "pg_catalog"."default",
  "ftp_id" varchar(255) COLLATE "pg_catalog"."default",
  "ftp_path" varchar(255) COLLATE "pg_catalog"."default",
  "ftp_username" varchar(255) COLLATE "pg_catalog"."default",
  "ftp_password" varchar(255) COLLATE "pg_catalog"."default",
  "key_word" varchar(255) COLLATE "pg_catalog"."default",
  "file_type" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_server_name" varchar(255) COLLATE "pg_catalog"."default",
  "share_folder_server_path" varchar(255) COLLATE "pg_catalog"."default",
  "table_name_dms" varchar(255) COLLATE "pg_catalog"."default",
  "table_name_delta" varchar(255) COLLATE "pg_catalog"."default",
  "table_name_ods" varchar(255) COLLATE "pg_catalog"."default",
  "etl_template" text COLLATE "pg_catalog"."default",
  "sheet_name" varchar(255) COLLATE "pg_catalog"."default",
  "usecols" varchar(255) COLLATE "pg_catalog"."default",
  "include_filename" varchar(255) COLLATE "pg_catalog"."default",
  "sftp_id" varchar(255) COLLATE "pg_catalog"."default",
  "sftp_username" varchar(255) COLLATE "pg_catalog"."default",
  "sftp_keyfile_name" varchar(255) COLLATE "pg_catalog"."default",
  "sftp_password" varchar(255) COLLATE "pg_catalog"."default",
  "sftp_path" varchar(255) COLLATE "pg_catalog"."default",
  "if_ts" varchar(255) COLLATE "pg_catalog"."default",
  "ts_command" text COLLATE "pg_catalog"."default",
  CONSTRAINT "upload_cfg_msg_pkey" PRIMARY KEY ("table_name")
)
;
